import { Link } from "react-router-dom";
import { WatchdogMark } from "@/components/WatchdogMark";

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section id={id} className="space-y-3">
      <h2 className="text-lg font-semibold text-foreground">{title}</h2>
      <div className="space-y-3 text-muted-foreground">{children}</div>
    </section>
  );
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background text-foreground">
      <header className="border-b border-border">
        <div className="max-w-3xl mx-auto px-6 py-4 flex items-center justify-between">
          <Link to="/" className="flex items-center gap-2">
            <WatchdogMark className="h-6 w-6" />
            <span className="font-semibold text-sm">Watchdog</span>
          </Link>
          <Link to="/login" className="text-sm text-muted-foreground hover:text-foreground transition-colors">
            Sign in
          </Link>
        </div>
      </header>

      <main className="max-w-3xl mx-auto px-6 py-16 space-y-12">
        <div className="space-y-2">
          <p className="text-xs font-mono text-muted-foreground uppercase tracking-widest">Legal</p>
          <h1 className="text-3xl font-bold">Privacy Policy</h1>
          <p className="text-sm text-muted-foreground">Effective date: 29 July 2026 &nbsp;·&nbsp; Controller: Watchdog</p>
        </div>

        <p className="text-muted-foreground leading-relaxed">
          Watchdog is a website uptime and security monitoring service. This policy explains what personal data we
          collect, why we collect it, how long we keep it, and your rights under the EU General Data Protection
          Regulation (GDPR) and UK GDPR.
        </p>

        <Section id="controller" title="1. Data Controller">
          <p>
            Watchdog operates as the data controller for personal data you provide when creating an account or using the
            service. Contact: <a href="mailto:saad.r0521@gmail.com" className="text-primary hover:underline">saad.r0521@gmail.com</a>.
          </p>
        </Section>

        <Section id="data-collected" title="2. Data We Collect">
          <p>We collect only what is necessary to provide the service:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li><strong className="text-foreground">Account data</strong> — email address, display name, bcrypt-hashed password.</li>
            <li><strong className="text-foreground">Monitor configuration</strong> — URLs and names of websites you choose to monitor. URLs may contain tokens or usernames if you include them.</li>
            <li><strong className="text-foreground">Alert channel settings</strong> — optional webhook URL, Slack URL, Discord URL, Telegram bot token and chat ID, browser push subscription.</li>
            <li><strong className="text-foreground">Check results</strong> — HTTP status, response time, SSL certificate data, header findings — generated by our monitoring probes, not supplied by you.</li>
            <li><strong className="text-foreground">Security events</strong> — login timestamps, IP addresses in audit logs (not persisted beyond 7 days of platform log rotation).</li>
          </ul>
          <p>We do <strong className="text-foreground">not</strong> collect payment card data, health data, or any special-category data.</p>
        </Section>

        <Section id="lawful-basis" title="3. Lawful Basis for Processing">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-border rounded-md overflow-hidden">
              <thead className="bg-card">
                <tr>
                  <th className="text-left px-4 py-2 text-foreground font-medium">Processing activity</th>
                  <th className="text-left px-4 py-2 text-foreground font-medium">Lawful basis</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                <tr className="bg-background/50">
                  <td className="px-4 py-2">Account management and authentication</td>
                  <td className="px-4 py-2">Contract — Art. 6(1)(b)</td>
                </tr>
                <tr>
                  <td className="px-4 py-2">Sending downtime / SSL / security alert emails</td>
                  <td className="px-4 py-2">Contract — Art. 6(1)(b)</td>
                </tr>
                <tr className="bg-background/50">
                  <td className="px-4 py-2">Storing monitor check results</td>
                  <td className="px-4 py-2">Contract — Art. 6(1)(b)</td>
                </tr>
                <tr>
                  <td className="px-4 py-2">Audit logging of security-sensitive actions</td>
                  <td className="px-4 py-2">Legitimate interest — Art. 6(1)(f) (fraud prevention, account security)</td>
                </tr>
              </tbody>
            </table>
          </div>
          <p>We send no marketing emails. All email communication is strictly operational (alerts you have configured).</p>
        </Section>

        <Section id="retention" title="4. Retention">
          <div className="overflow-x-auto">
            <table className="w-full text-sm border border-border rounded-md overflow-hidden">
              <thead className="bg-card">
                <tr>
                  <th className="text-left px-4 py-2 text-foreground font-medium">Data</th>
                  <th className="text-left px-4 py-2 text-foreground font-medium">Retention period</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-border">
                <tr className="bg-background/50">
                  <td className="px-4 py-2">Account data (name, email, password hash)</td>
                  <td className="px-4 py-2">Until account is hard-deleted (30-day grace period after deletion request)</td>
                </tr>
                <tr>
                  <td className="px-4 py-2">Monitor check results</td>
                  <td className="px-4 py-2">90 days</td>
                </tr>
                <tr className="bg-background/50">
                  <td className="px-4 py-2">Resolved incidents and alerts</td>
                  <td className="px-4 py-2">1 year</td>
                </tr>
                <tr>
                  <td className="px-4 py-2">Session refresh tokens</td>
                  <td className="px-4 py-2">7 days (automatically expired)</td>
                </tr>
                <tr className="bg-background/50">
                  <td className="px-4 py-2">Platform logs (IP addresses)</td>
                  <td className="px-4 py-2">7 days (Railway default log rotation)</td>
                </tr>
              </tbody>
            </table>
          </div>
        </Section>

        <Section id="cookies" title="5. Cookies and Local Storage">
          <p>
            Watchdog uses a single <strong className="text-foreground">HttpOnly, Secure, SameSite=Strict</strong> cookie
            to maintain your session. This cookie is strictly necessary for the service to function and does not require
            your consent under GDPR / the ePrivacy Directive.
          </p>
          <p>We use no analytics cookies, advertising cookies, or third-party tracking pixels.</p>
        </Section>

        <Section id="sub-processors" title="6. Sub-Processors (Data Processors)">
          <p>
            We share data with the following sub-processors solely to operate the service. All are contractually bound
            to process data only on our instructions.
          </p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li><strong className="text-foreground">Railway</strong> (cloud hosting, PostgreSQL) — United States</li>
            <li><strong className="text-foreground">Resend</strong> (transactional email) — United States</li>
            <li><strong className="text-foreground">Cloudflare</strong> (CDN, DDoS protection) — United States / Global</li>
          </ul>
          <p>
            Transfers to US-based processors rely on Standard Contractual Clauses (SCCs). A full sub-processor list is
            maintained internally and available on request.
          </p>
        </Section>

        <Section id="your-rights" title="7. Your Rights">
          <p>Under GDPR you have the following rights, exercisable at any time by contacting us or using the in-app controls:</p>
          <ul className="list-disc list-inside space-y-1 pl-2">
            <li><strong className="text-foreground">Access</strong> — request a copy of your personal data.</li>
            <li><strong className="text-foreground">Rectification</strong> — correct inaccurate data via Settings.</li>
            <li><strong className="text-foreground">Erasure</strong> — delete your account in Settings. All data is hard-deleted after a 30-day grace period.</li>
            <li><strong className="text-foreground">Portability</strong> — download your data as JSON via Settings → Export Data.</li>
            <li><strong className="text-foreground">Restriction</strong> — request that we restrict processing of your data while a dispute is pending.</li>
            <li><strong className="text-foreground">Object</strong> — object to processing based on legitimate interest.</li>
            <li><strong className="text-foreground">Complaint</strong> — lodge a complaint with your national supervisory authority (e.g. ICO in the UK, your local DPA in the EU).</li>
          </ul>
          <p>
            To exercise any right, email{" "}
            <a href="mailto:saad.r0521@gmail.com" className="text-primary hover:underline">saad.r0521@gmail.com</a>.
            We respond within 30 days.
          </p>
        </Section>

        <Section id="security" title="8. Security">
          <p>
            We protect your data with bcrypt password hashing, short-lived JWTs, HttpOnly session cookies,
            HTTPS/HSTS enforcement, account lockout after failed logins, RBAC, and an append-only audit log for
            security-sensitive actions. See our{" "}
            <a href="https://github.com/saad-r10/watchdog/blob/main/docs/security-policy.md" className="text-primary hover:underline" target="_blank" rel="noopener noreferrer">
              Security Policy
            </a>{" "}
            for responsible disclosure and patching SLAs.
          </p>
        </Section>

        <Section id="breach" title="9. Data Breach Notification">
          <p>
            In the event of a personal data breach, we will notify the relevant supervisory authority within 72 hours of
            becoming aware of it (GDPR Article 33). Where the breach is likely to result in a high risk to you, we will
            also notify you directly without undue delay (Article 34).
          </p>
        </Section>

        <Section id="changes" title="10. Changes to This Policy">
          <p>
            We may update this policy. Material changes will be communicated by email or an in-app notice at least 14
            days before they take effect. The effective date at the top of this page reflects the most recent revision.
          </p>
        </Section>

        <Section id="contact" title="11. Contact">
          <p>
            Questions about this policy or your data:{" "}
            <a href="mailto:saad.r0521@gmail.com" className="text-primary hover:underline">saad.r0521@gmail.com</a>.
          </p>
        </Section>
      </main>

      <footer className="border-t border-border mt-16">
        <div className="max-w-3xl mx-auto px-6 py-6 flex items-center justify-between text-xs text-muted-foreground">
          <span>© 2026 Watchdog</span>
          <Link to="/" className="hover:text-foreground transition-colors">Back to home</Link>
        </div>
      </footer>
    </div>
  );
}
